apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3 # Number of desired replicas
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: sudalaimmanis/flaskapp:latest
        ports:
        - containerPort: 3000  # Port your application listens on
